### ISSUE TITLE
CI gets built twice, on both Travis “com” and “org” versions

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/rnpgp.com#12]
“org” build fails because environment variables are missing. I have disabled some switches in https://travis-ci.org/riboseinc/rnpgp.com/settings, @ronaldtse could you also switch it off globally on https://travis-ci.org/organizations/riboseinc/repositories?

**Comment by ronaldtse** [comment]
@strogonoff turned off rnpgp.com at travis-ci.org . Thanks!
