### ISSUE TITLE
Support rnpgp.com (without the www)

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnpgp.com#3]
I only just realized today that there is actually content on the site. o.o

The reason is, I have been going to:
[https://rnpgp.com](https://rnpgp.com)
[http://rnpgp.com](http://rnpgp.com)

Both of which present different errors without the 'www'.
Maybe you're already aware, but I figured I would report it.

**Comment by ronaldtse** [comment]
This is very strange, it was working couple days ago. Thanks for reporting, will fix.

**Comment by ronaldtse** [comment]
@dewyatt the issue's fixed now. Thanks for reporting!

**Comment by strogonoff** [comment]
Thanks @dewyatt for bringing this up. Turns out rnpgp.com still has the sample blog post up and the site uses an old version of Open Project theme, should be fixed in #4 soon.
