### ISSUE TITLE
Fix sample content & update theme

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/rnpgp.com#4]

**Comment by ronaldtse** [comment]
@dewyatt could we bother you for an introductory blog post to RNP? 😉

**Comment by strogonoff** [comment]
@dewyatt I concur, if you’re interested to try it’d be great if you write a post about the project. Don’t worry about perfect writing, the post will be reviewed and possibly edited during the merge.

If you’re not into writing, let me know, I’ll talk with you and Ronald to collect the material for the post, and then I’ll ask you to review post drafts before it goes live on rnpgp.com.

**Comment by dewyatt** [comment]
@strogonoff @ronaldtse I'm not that great when it comes to writing ([sample](https://dewyatt.github.io/articles/seagate-external-drive-leds-in-linux), [more](https://dewyatt.github.io/articles/)), and it tends to take me an exceptionally large amount of time to actually churn something out.

Also I feel like my TODO list keeps growing and I'd rather avoid adding to it if at all possible. :)

**Comment by ronaldtse** [comment]
@dewyatt would it help if @strogonoff can ask you some questions on the phone/Skype? 😉

**Comment by strogonoff** [comment]
Moving further discussion to #9 as the advertised purpose of this issue has long been fulfilled (sample content removed & theme version bumped).
