### ISSUE TITLE
Deployment not working?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/rnpgp.com#5]
The site was updated in https://github.com/riboseinc/rnpgp.com/commit/9441bc21b07cc747113e431b6487a00d7ec11d12 as of 40+ minutes ago, but www.rnpgp.com still shows the old version. Build time can’t be that long for project sites. There’s no indicator of CI status here.

Could it be that build failed, or is the problem in CF cache?

(I’m filing this on Sunday but this is not urgent and can wait for next convenient workday, of course. Perhaps we can tackle CF cache invalidation in CI eventually.)

**Comment by strogonoff** [comment]
I see updated site now, wonder if that was due to a manual action or perhaps CF cache is too short…

**Comment by ronaldtse** [comment]
Ah -- because the CI instance is a private one, it polls every hour rather than gets called by webhooks. I've now shortened the interval to 5 minutes. Thanks for reporting!

**Comment by strogonoff** [comment]
Got it, I was worrying CF cache logic needed to be looked at.

www.riffol.com should also be possible to deploy, perhaps CI will pick it up in a bit.
