### ISSUE TITLE
Update RNP logo and associated site colors

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnpgp.com#7]
Logo uploaded here:
https://github.com/riboseinc/open-design/tree/master/rnp/logos

**Comment by strogonoff** [comment]
(In progress, CI pending)

<img width="1548" alt="screen shot 2018-09-01 at 9 33 06 am" src="https://user-images.githubusercontent.com/292959/44940476-1610d100-adca-11e8-9ef1-36616ba5f931.png">
